<?
return array(
	array(
		'link' => 'https://iwarm-on.ru/catalog/product/view/id/1979/category/585/',
		'img' => '/uploads/1.jpg',
		'name' => 'Кабель нагревательный саморегулирующийся 17КСТМ2-АТ (на метраж)',
		'price' => '165',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/kabel-nagrevatel-nyj-samoregulirujuschijsja-17kstm2-t-na-metrazh',
		'img' => '/uploads/2.jpg',
		'name' => 'Кабель нагревательный саморегулирующийся 17КСТМ2-Т (на
		метраж)',
		'price' => '231',
	),
	array(
		'link' => 'https://iwarm-on.ru/catalog/product/view/id/1980/category/585/',
		'img' => '/uploads/3.png',
		'name' => 'Кабель нагревательный саморегулирующийся 17КСТМ2-АТ (бухта 100м)',
		'price' => '16500',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/kabel-nagrevatel-nyj-samoregulirujuschijsja-17kstm2-t-l-100-m',
		'img' => '/uploads/4.png',
		'name' => 'Кабель нагревательный саморегулирующийся 17КСТМ2-Т (L=100 м)',
		'price' => '23001',
	),
	array(
		'link' => 'https://iwarm-on.ru/catalog/product/view/id/1981/category/585/',
		'img' => '/uploads/5.png',
		'name' => 'Кабель нагревательный саморегулирующийся 17КСТМ2-АТ (катушка 200м)',
		'price' => '33800',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/kabel-nagrevatel-nyj-samoregulirujuschijsja-17kstm2-t-na-katushke-l-200m',
		'img' => '/uploads/6.png',
		'name' => 'Кабель нагревательный саморегулирующийся 17КСТМ2-Т на катушке (L=200м)',
		'price' => '46000',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/kabel-nagrevatel-nyj-samoregulirujuschijsja-30kstm2-t',
		'img' => '/uploads/7.jpg',
		'name' => 'Кабель нагревательный саморегулирующийся 30КСТМ2-Т',
		'price' => '247',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/kabel-nagrevatel-nyj-samoregulirujuschijsja-30kstm2-t-buhta-100m',
		'img' => '/uploads/8.png',
		'name' => 'Кабель нагревательный саморегулирующийся 30КСТМ2-Т (бухта 100м)',
		'price' => '24433',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/kabel-nagrevatel-nyj-samoregulirujuschijsja-30kstm2-t-katushka-200m',
		'img' => '/uploads/9.png',
		'name' => 'Кабель нагревательный саморегулирующийся 30КСТМ2-Т (катушка 200м)',
		'price' => '48865',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/kabel-nagrevatel-nyj-samoregulirujuschijsja-30kstm2-at',
		'img' => '/uploads/10.png',
		'name' => 'Кабель нагревательный саморегулирующийся 30КСТМ2-АТ',
		'price' => '221',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/kabel-nagrevatel-nyj-samoregulirujuschijsja-30kstm2-at-l-100m',
		'img' => '/uploads/11.png',
		'name' => 'Кабель нагревательный саморегулирующийся 30КСТМ2-АТ (L=100м)',
		'price' => '21928',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/kabel-nagrevatel-nyj-samoregulirujuschijsja-30kstm2-at-katushka-200m',
		'img' => '/uploads/12.png',
		'name' => 'Кабель нагревательный саморегулирующийся 30КСТМ2-АТ (катушка 200м)',
		'price' => '43853',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-17vc2-f',
		'img' => '/uploads/13.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 17VC2-F',
		'price' => '1931',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-31vc2-f',
		'img' => '/uploads/14.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 31VC2-F',
		'price' => '1931',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-40vc2-f',
		'img' => '/uploads/15.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 40VC2-F',
		'price' => '1931',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-60vc2-f',
		'img' => '/uploads/16.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 60VC2-F',
		'price' => '1931',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-23vl2-t',
		'img' => '/uploads/17.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 23VL2-T',
		'price' => '583',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-27vl2-t',
		'img' => '/uploads/18.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 27VL2-T',
		'price' => '583',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-11vm2-t',
		'img' => '/uploads/19.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 11VM2-T',
		'price' => '417',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-17vm2-t',
		'img' => '/uploads/20.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 17VM2-T',
		'price' => '417',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-11vr2-f',
		'img' => '/uploads/21.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 11VR2-F',
		'price' => '817',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-11vr2-t',
		'img' => '/uploads/22.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 11VR2-T',
		'price' => '655',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-17vr2-f',
		'img' => '/uploads/23.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 17VR2-F',
		'price' => '817',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-17vr2-t',
		'img' => '/uploads/24.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 17VR2-T',
		'price' => '655',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-27vr2-f',
		'img' => '/uploads/25.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 27VR2-F',
		'price' => '817',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-27vr2-t',
		'img' => '/uploads/26.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 27VR2-T',
		'price' => '655',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-31vr2-f',
		'img' => '/uploads/27.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 31VR2-F',
		'price' => '817',
	),
	array(
		'link' => 'https://iwarm-on.ru/akcii/unikal-noe-predlozhenie-mesjaca-samoregulirujuschijsja-kabel/samoregulirujuschajasja-jelektricheskaja-nagrevatel-naja-lenta-31vr2-t',
		'img' => '/uploads/28.jpg',
		'name' => 'Саморегулирующаяся электрическая нагревательная лента 31VR2-T',
		'price' => '655',
	),
);
